### PR TITLE
Add missing examples/__init__.py

### PR DESCRIPTION
**Pull request by adsharma**
Required for:

```
python3 -m examples.case_study
```

### CODE REVIEW

**Comment by mwhittaker** [comment]
What happens when you run `python3 -m examples.case_study`? For me, it runs fine without needing an `__init__.py` file in in the `examples/` directory.

**Comment by adsharma** [comment]
```
$ python3 -m examples.case_study
/usr/bin/python3: No module named examples.case_study
$ touch examples/__init__.py
$ python3 -m examples.case_study
0-resilient Capacities
2291.6023550039754
3666.5637680063605
4200.2161213962345
4124.884156509473

0-resilient Searched
```

**Comment by adsharma** [comment]
Guessing you have examples module accessible from somewhere else in your sys.path.

**Comment by mwhittaker** [comment]
Interesting! Yeah, I can't say I fully understand how Python goes looking for stuff. Thanks for the PR!

**Comment by adsharma** [comment]
More discussion on the topic:

https://github.com/python/mypy/issues/2773

without the __init__.py it's possible that mypy will ignore the directory
and not type check an entire module. But things got complicated with
certain limited module types that can be added without a __init__.py in
python3.

**Pull request merged**
