### PR TITLE
Fixes for type check errors exposed by pyright

### PR DESCRIPTION
**Pull request by adsharma**
Use SupportsLessThan to indicate that TypeVar T should be
comparable.

### CODE REVIEW

**Comment by mwhittaker** [comment]
Wow, this is great! I've been targeting Python 3.6, and I think the Protocol stuff is a newer feature? Could we split out the Python 3.6 compatible stuff from the non Python 3.6 compatible stuff? I'd love to merge as much of this as possible. Or maybe, we should just require a newer Python version? I'm not sure, what do you think?

**Comment by adsharma** [comment]
Protocols are python3.8, created in 2017, accepted in 2019.

https://www.python.org/dev/peps/pep-0544/

I believe backports are available via:

https://pypi.org/project/typing-extensions/

**Comment by adsharma** [comment]
My general preference is to avoid python2, support python releases from 2-4 years ago. python3.6 was released Dec 2016.

Alternatively, you can target the python versions in the "long term supported" largest/popular linux distributions: ubuntu 18.04 (3.6) and 20.04 (3.8) as of today.

**Comment by mwhittaker** [comment]
Got it. I updated to Python 3.8 and merged this in! Thanks again for the pull request. I really appreciate you checking out the repo and improving it :)

**Comment by mwhittaker** [comment]
Fixes #4.

**Pull request merged**
